- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- MTGFamiliar/src/main/res/values/arrays.xml
- MTGFamiliar/src/main/res/values/strings.xml
Searching for uncommons didn't work in spanish, and future tranlations could be affected as well.
See issue: https://github.com/AEFeinstein/mtg-familiar/issues/62
> Fix criteria generation for the Rarity search filter in all locales

- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/FamiliarActivity.java
- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/fragments/JudgesCornerFragment.java
- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/helpers/PreferenceAdapter.java
- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/DbUpdaterService.java
- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/MTRIPGParser.java
- MTGFamiliar/src/main/res/raw/jar.html
- MTGFamiliar/src/main/res/values/strings-pref-keys.xml
- MTGFamiliar/src/main/res/values/strings.xml
- gradle/wrapper/gradle-wrapper.properties
Per the request in issue #53, this adds the Judging at Regular document in the Judge's Corner. I wasn't sure how the document was created, but it looked like the .pdb file was downloaded from BlueWizard.net and then converted to an HTML document by using Calibre. So that's what I did, and I uploaded the file to my Google Drive at https://drive.google.com/file/d/0Bxp8EZC9AHuyVHc4TmVLUkpza0k/view?usp=sharing.
We'll probably want to move this file to the same location as the rest of the files and change the URL in MTRIPGParser.java
> Judging at regular

- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/helpers/PriceFetchRequest.java
Resolves issue #66 by adding a check for basic land type and adding the card number in parentheses.
> Wishlist land

- MTGFamiliar/src/main/java/com/gelakinetic/mtgfam/fragments/TradeFragment.java
> long click removal for trades

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/RulesParser.java
> Check if the last glossary term has been added to the list.

- README.md
Don't know if you want to add it, but it looks nice :-).
> Add F-Droid link to Readme.

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/WishlistHelpers.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
Refactoring a couple things in the wishlist dialog that might have been slowing down over cards that are in a large amount of sets (the basic lands.)
Biggest change is saving the sets that can be foil in a HashSet, rather than querying the database about which sets are modern on every single set.
> #27 Speed up basic land usage in wishlist.

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
Refactored some joins into a "IN" expression with subquery in the WHERE clause (significant speed boost).
Also modified banned checks for another small speed boost.
> Modified parts of the search SQL query for speed gain. Should at least improve the situation with slow format-specific queries.

- mobile/src/main/res/values-pt/strings.xml
Translation for portuguese had some grammar mistakes, and some translations were very weird (For portuguese speakers).
> Better translation for portuguese

- mobile/src/main/java/com/gelakinetic/GathererScraper/JsonTypes/Card.java
- mobile/src/main/java/com/gelakinetic/GathererScraper/JsonTypes/Expansion.java
- mobile/src/main/java/com/gelakinetic/GathererScraper/JsonTypes/LegalityData.java
- mobile/src/main/java/com/gelakinetic/GathererScraper/JsonTypes/Manifest.java
- mobile/src/main/java/com/gelakinetic/GathererScraper/JsonTypes/Patch.java
- mobile/src/main/java/com/gelakinetic/GathererScraper/PrefixedFieldNamingStrategy.java
- mobile/src/main/java/com/gelakinetic/mtgfam/FamiliarActivity.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/MtgSet.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/PreferenceAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/CardAndSetParser.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/DbUpdaterService.java
Based on the v2 json format used in the commit 7d27bcac31dfff29f0a9c51dc5e6a85cb7a06f67  of GathererScraper.
> Update json parsing to patch-v2 (using gson)

- build.gradle
- mobile/build.gradle
- mobile/proguard-rules.txt
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-it/strings.xml
- mobile/src/main/res/values-pl/strings.xml
- mobile/src/main/res/values-pt/strings.xml
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
Added new strings for translation
Updated dependencies
> Foreign names

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/SearchCriteria.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/res/layout/search_frag.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values/strings.xml
I am not sure about the wording... maybe something better could be done. Something like: "Mana has {X}"
Where we could replace {X} with the appropriate image.
Fixes issue #11.
> Added option to search for "X" symbol in mana cost. Fix enhancement issue #11.

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
The trick is to concat leading and trailing spaces to the db column, then search for the desired type with leading and trailing spaces.
> Don't search substrings for types #154

- mobile/src/main/res/values/arrays.xml
Emrakul, the Promised End has a CMC of 13.
> Update MoJhoSto cmc spinner for EMN

- mobile/build.gradle
- mobile/src/main/java/com/tokenautocomplete/CharacterTokenizer.java
- mobile/src/main/java/com/tokenautocomplete/CountSpan.java
- mobile/src/main/java/com/tokenautocomplete/FilteredArrayAdapter.java
- mobile/src/main/java/com/tokenautocomplete/HintSpan.java
- mobile/src/main/java/com/tokenautocomplete/TokenCompleteTextView.java
- mobile/src/main/java/com/tokenautocomplete/ViewSpan.java
Fix for issue reported by #253. Same changes as splitwise/TokenAutoComplete#329.
> Fixed IndexOutOfBoundsExceptions

- mobile/src/main/java/com/gelakinetic/mtgfam/FamiliarActivity.java
- mobile/src/main/java/com/gelakinetic/mtgfam/MtgAppWidgetConfigure.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/DecklistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/FamiliarListFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/LifeCounterFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ManaPoolFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/MoJhoStoFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/PrefsFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ProfileFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ResultListFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/RoundTimerFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/TradeFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/WishlistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/FamiliarActivityDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/ProfileDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/RoundTimerDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/TradeDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/WishlistDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/ImageGetterHelper.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/LcPlayer.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/MTGFamiliarAppWidgetProvider.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/PreferenceAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/RoundTimerBroadcastReceiver.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/TutorCards.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/CardAndSetParser.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/DbUpdaterService.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/MTRIPGParser.java
All PreferenceAdapter methods now take a Context as a parameter
apply() is used instead of commit() to write SharedPreferences
> Made all PreferenceAdapter methods "public static synchronized"

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/SelectableItemAdapter.java
> Catch IndexOutOfBounds instead

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/TradeFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/CardViewDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/DecklistDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/FamiliarDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/GatheringsDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/LcPlayerDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/LifeCounterDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/ProfileDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/ResultListDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/RulesDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/SearchViewDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/SortOrderDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/TradeDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/WishlistDialogFragment.java
After I added the @Nullable attribute, I went through and fixed all the places Android Studio said a NullPointerException may be thrown.
> Added @Nullable Attribute to Where Dialogs Access Parents

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ResultListFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/WishlistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/CardHelpers.java
Fixes concurrency issues when reading the wishlist.
Fixes adding cards to the wishlist from the result list.
> Merge master into FixListSelectors

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
> Support EXCLUDE_TOKEN in type fields.

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/SearchCriteria.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/res/layout/search_frag.xml
- mobile/src/main/res/values/strings.xml
Adds feature requested in #306, searching by watermark
> Search by watermark

- build.gradle
- mobile/src/main/java/com/gelakinetic/mtgfam/FamiliarActivity.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/DecklistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/MoJhoStoFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ResultListFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/RulesFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/WishlistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/DecklistDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/RulesDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/TradeDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/CardHelpers.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/LookupAllPricesTest.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/MtgCard.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/DatabaseManager.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/FamiliarDbHandle.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/MarketPriceFetcher.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/DbUpdaterService.java
Using finally{} is a little safer
> Balance db open close

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/MarketPriceInfo.java
> Default to Market Price if Price is Zero

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/FamiliarGlideTarget.java
- mobile/src/main/res/layout/card_view_frag.xml
Don't measure the layout when displaying images in the main view
Do measure the layout when displaying images for a dialog
Replaced separate scroll views for card image and text with one
Removed unused whereTo
Fixes #402
> Fix issue with card images not being full screened

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/DecklistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/RulesFragment.java
Deck legality check now takes into account deck size
Deck legality check now allows multiple basics for Commander / Brawl
Takes care of #392
> Added support for Brawl

- build.gradle
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/HtmlDocFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/updaters/MTRIPGParser.java
The documents for #365 are already live
> #365 WebView tweaks to handle the new judge docs elegantly

- mobile/src/main/res/values-pt/strings.xml
I changed some things that didn't make much sense and some inconsistencies.
For example, Judge's Corner is now translated accurately (it was translated do Corner Judge, which always bugged me, being a judge that uses the feature a lot) and the whole Gathering feature on the Life Totals section now makes sense (I didn't even know it existed because the previous translation didn't convey its purpose).
> Changes to Portuguese Translation

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/SearchViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/PreferenceAdapter.java
- mobile/src/main/res/values/strings-pref-keys.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Resolves #434, still needs translation
> Added option to not persist search options

- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/JsonObjects/CategoryGroups.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/JsonObjects/ProductDetails.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/JsonObjects/ProductInformation.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/MarketPriceFetcher.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/MarketPriceInfo.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/tcgp/TcgpApi.java
> Updated TCGPlayer.com API and data structures to 1.17.0

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/com/gelakinetic/mtgfam/FamiliarActivity.java
> Update supported URLs

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/TradeFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/SortOrderDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/CardHelpers.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/WishlistHelpers.java
> Add More Sorting Options

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/RulesFragment.java
Use a name based query to find the card when the you click on it.
> #370 Make Banned & Restricted cards in the Rules Clickable

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/CardViewFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/MoJhoStoFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/ResultListFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/dialogs/TradeDialogFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/CardHelpers.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/LookupAllPricesTest.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/MtgCard.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/PreferenceAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardDbAdapter.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/database/CardSearchProvider.java
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings-pref-keys.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Should close #185.
Very nice app, by the way. Thanks a lot.
> search for cards in non-english languages

- mobile/src/main/java/com/gelakinetic/mtgfam/fragments/DecklistFragment.java
- mobile/src/main/java/com/gelakinetic/mtgfam/helpers/CardHelpers.java
> Fix decklist order and type headers
